---
name: Release
on:
  # https://github.com/actions/runner/issues/1007
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        id: go
        with:
          go-version: ^1.19

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Launch goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release
          ldflags: -s -w
            -X github.com/vicenteherrera/psa-checker/cmd/psa-checker.version={{.Version}}
            -X github.com/vicenteherrera/psa-checker/cmd/psa-checker.commit={{.Commit}}
            -X github.com/vicenteherrera/psa-checker/cmd/psa-checker.date={{.Date}}
            -X github.com/vicenteherrera/psa-checker/cmd/psa-checker.builtBy=goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}